#!/usr/bin/env bash
# \" redireects ip \"

only_one () {
    echo "The subdomain $2 is a ""$(dig +noall +answer "$2"."$1" | awk '{print $4}')"" record and points to ""$(dig +short "$2"."$1")"
}

if [ $# -eq 1 ]
then
    only_one "$1" "www"
    only_one "$1" "lb-01"
    only_one "$1" "web-01"
    only_one "$1" "web-02"
elif [ $# -eq 2 ]
then
    only_one "$1" "$2"
fi
