#!/usr/bin/env bash
# configurating nginx listening the 80 port
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
