#!/usr/bin/env bash
# configurating nginx listening the 80 port
sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
