#!/usr/bin/env bash
# configurating nginx listening the 80 port
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
url="google.com"
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me $url" /etc/nginx/sites-available/default
service nginx start
