#!/usr/bin/env bash
#lets us know what server is using
sudo sed '/listen [::]:80 default_server;/a add_header X-Served-By 1634-web-01;' /etc/nginx/sites-available/default > /etc/nginx/sites-available/default
sudo service nginx restart
