#!/usr/bin/env bash
#manages different signals, creates and deleates files with its pid inside
trap funct1 15
trap funct2 2
trap funct 3
funct3()
{
    rm var/run/holbertonscript.pid
}
funct1()
{
    echo "I hate the kill command"
    rm var/run/holbertonscript.pid
}
funct2()
{
    echo "Y U no love me?!"
}
pid_var="$(grep ^Pid: /proc/self/status | awk '{print $2}')"
echo "$pid_var" > /var/run/holbertonscript.pid
x=1
while [ $x -eq 1 ]
do
    echo "To infinity and beyond"
done
