#!/usr/bin/env bash
#manages different signals, creates and deleates files with its pid inside
trap funct1 15
trap funct2 2
trap funct3 3
funct3()
{
    rm var/run/holbertonscript.pid
    exit
}
funct1()
{
    echo "I hate the kill command"
    rm var/run/holbertonscript.pid
    exit
}
funct2()
{
    echo "Y U no love me?!"
}
echo "$$" > /var/run/holbertonscript.pid
x=1
while [ $x -eq 1 ]
do
    echo "To infinity and beyond"
done
