#!/usr/bin/env bash
#manages another process
if [ "$1" == "start" ]
then
    ./manage_my_process &
    pgrep -f manage_my_process > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
    echo "manage_my_process stopped"
    kill $(cat /var/run/my_process.pid)
    rm /var/run/my_process.pid
elif [ "$1" == "restart" ]
then
    kill $(cat /var/run/my_process.pid)
    rm /var/run/my_process.pid
    echo "manage_my_process restarted"
    ./manage_my_process &
    pgrep -f manage_my_process > /var/run/my_process.pid
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
