#!/usr/bin/env bash
#FizzBuzz from 1 to 100
for (( x=1; x<=100; x++))
do
    if [ $(( x % 3 )) -eq 0 ]
    then
	if [ $(( x % 5 )) -eq 0 ]
	then
	    echo "FizzBuzz"
	else
	    echo "Fizz"
	fi
    elif [ $(( x % 5)) -eq 0 ]
    then
	echo "Buzz"
    else
	echo "$x"
    fi
done
