#!/usr/bin/env bash
#displays Holberton School 10 times,in 9th iteration + Hi on a new line.
#!/bin/bash
x=1
while [ $x -le 10 ]
do
    echo "Holberton School"
    if [ $x -eq 9 ]
    then
	echo "Hi"
    fi
    ((x++))
done
