#!/usr/bin/env bash
#4 bad luck from China, 9 bad luck from Japan, 17 bad luck from Italy
x=1
while [ $x -le 20 ]
do
    case $x in
	4) echo "bad luck from China"
	   ;;
	9) echo "bad luck from Japan"
	   ;;
	17) echo "bad luck from Italy"
	    ;;
	*)
	    echo "$x"
    esac
    ((x++))
done
